### ISSUE TITLE
Come up with Pin Design

### ISSUE THREAD

**Issue by benreyhani15** [Night-O/AndroidClient#9]
Need new design for what to indicate the venues on the map as;

Originally; have pie chart like figures that indicated guy to girl ratio right on the map and it flames up when a club is hot.

@wangart was against the flame idea as he said it would could be bad for the clubs that we support. 

Other ideas:

Have an icon similar to what is displayed on phone's to show the signal strength, 1-4 bars.  4 bars beside the club would indicate that it's poppin, then any club that is our customer we won't allow it to go below 2-3 bars.  

@shuruli & @wangart  discuss this here with ideas.

**Comment by shuruli** [comment]
@wangart We need to discuss this at some point this week if you are free.

**Comment by benreyhani15** [comment]
@wangart for UI stuff look into these sources:

https://medium.com/@AngelosArnis/top-favorite-design-resources-ec50f0f78f35#.6npi3riok
